package com.onlythinking.shop.mgt.system.mapper;

import com.onlythinking.shop.mgt.system.model.OtSysUserView;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

/**
 * <p> This was generated by Ot Mybatis generator. </p>
 *
 * @author lixingping
 * Date 2019-02-22 21:42:02
 */
@Mapper
public interface OtSysUserDtoMapper {
    List<OtSysUserView> getSysUserList(Map<String, Object> params);
}
