package com.onlythinking.shop.mgt.system.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * <p> This was generated by Ot Mybatis generator. </p>
 *
 * @author lixingping
 * Date 2019-02-22 21:42:02
 */
@Mapper
public interface OtSysSystemMapper {

    String getLastTypeDicCode();

    String getLastDicCode(@Param("typeCode") String typeCode);
}
